version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - |
        if ! type mvn > /dev/null 2>&1; then
          echo "Maven not found, installing..."
          yum install -y maven
        else
          echo "Maven already installed, version: $(mvn --version)"
        fi
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DskipTests  # Package the application into a JAR, skipping tests for faster build
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Build and package completed on `date`

artifacts:
  files:
    - target/*.jar  # Replace with the path to your JAR file

cache:
  paths:
    - '/root/.m2/**/*'  # Caching Maven dependencies to speed up future builds
